### ISSUE TITLE
Library doesn't work with websockets v5

### ISSUE THREAD

**Issue by damouse** [beerfactory/hbmqtt#134]
The newest release of [websockets](https://pypi.org/project/websockets/) (v5.0) doesnt work with `htmqtt` 0.9.2. It worked with 4.x.x, but now raises:

```
...
  File "/usr/local/lib/python3.6/dist-packages/hbmqtt/client.py", line 21, in <module>
    from websockets.handshake import InvalidHandshake
ImportError: cannot import name 'InvalidHandshake'
```

Seems the two options are to release a new version of the library that works with websockets v5 or to pin the version of the dependency so the newest version is not installed.

**Comment by damouse** [comment]
Nevermind, already addressed in a [PR](https://github.com/beerfactory/hbmqtt/pull/132)
