### ISSUE TITLE
ImportError: cannot import name 'InvalidHandshake'

### ISSUE THREAD

**Issue by belyalov** [beerfactory/hbmqtt#138]
It doesn't work with `python 3.6.5` and latest version of `websockets`:

```bash
$ pip3 list
...
hbmqtt (0.9.2)
docopt (0.6.2)
passlib (1.7.1)
PyYAML (3.12)
transitions (0.6.8)
websockets (5.0.1)
```

```python
>>> import hbmqtt.client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/hbmqtt/client.py", line 21, in <module>
    from websockets.handshake import InvalidHandshake
ImportError: cannot import name 'InvalidHandshake'
```

Just because of.. `InvalidHandshake` looks to be moved into `websocket` from `websockets.handshake`:

```python
>>> from websockets.handshake import InvalidHandshake
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'InvalidHandshake'
>>>
>>> from websockets import InvalidHandshake
```

**Comment by bholly** [comment]
I'm having the same issue. You could also use

from websockets.exceptions import InvalidHandshake

However, waiting eagerly for a fix.

**Comment by payne92** [comment]
As a short term workaround, you can create a virtual environment and drop back to version 4.0.1 of websockets:

$ `pip3 install websockets==4.0.1`

And for the developers, FWIW, a simple, unqualified import seems to work in both websockets 4.0.1 and the latest 5.* versions:

`from websockets import InvalidHandshake`

See:  https://github.com/aaugustin/websockets/blob/5.0.1/websockets/__init__.py#L4

**Comment by bholly** [comment]
Thanks for the hint. We are already using the websockets==4.0.1 workaround.

**Comment by hongquan** [comment]
It is fixed in # #132 but unfortunately, @njouanin hasn't published to PyPI yet.

**Comment by njouanin** [comment]
Fixed by #132 , released in hbmqtt 0.9.3
